export const Users = [
  {
    id:1,
    desc: "hello post",
    profilePicture: "./1.jpeg",
    username: "Violet Namusisi",
  },
  {
    id:2,
    profilePicture: "./assets/person/2.jpeg",
    username: "Jane Birungi",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Allen Nakanwagi",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Candidates = [
  {
    id: 1,
    desc: "My name is Grace, 32 years old, married with 1 child. I have been working as a domestic worker for 14 years. I believe I from my skills I will be of value to your family. My main duty is house keeping and child care.",
    photo: "assets/post/1.jpeg",
    date: "1 week ago",
    age: 22,
    experience: 2,
    userId: 1,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "2 days ago",
    age: 25,
    experience: 1,
    userId: 2,
    desc: "My name is Grace, 32 years old, married with 1 child. I have been working as a domestic worker for 14 years. I believe I from my skills I will be of value to your family. My main duty is house keeping and child care.",
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    age: 26,
    userId: 3
  },
  {
    id: 4,
    desc: "My name is Grace, 32 years old, married with 1 child. I have been working as a domestic worker for 14 years. I believe I from my skills I will be of value to your family. My main duty is house keeping and child care.",
    photo: "assets/post/4.jpeg",
    date: "1 month ago",
    age: 28,
    experience: 4,
    userId: 4
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "2 months ago",
    age: 23,
    experience: 7,
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    age: 32,
    experience: 2,
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    age: 38,
    experience: 10,
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    age: 21,
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    age: 19,
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    age: 33,
    userId: 10,
    like: 104,
    comment: 12,
  },
];
